### ISSUE TITLE
release checklist

### ISSUE THREAD

**Issue by felixboehm** [owncloud/impersonate#53]
Open
- [ ] info.xml https://github.com/owncloud/impersonate/issues/55
- maybe #42 
- maybe a nicer Makefile 
- [ ] Adjust docs https://github.com/owncloud/documentation/issues/3441

QA 
- [x] [create release branch](http://endoflineblog.com/oneflow-a-git-branching-model-and-workflow#starting-a-release-branch)
- [ ] bump version
- [ ] create testplan and test cases Link: todo
  - see input here #29 
- [ ] test and document in testplan, including know issues. Final release "Go"

Build
- [ ] CHANGELOG.md
- [ ] sign and build tarball
- [ ] [tag and merge release branch](http://endoflineblog.com/oneflow-a-git-branching-model-and-workflow#finishing-a-release-branch)
- [ ] upload to marketplace
- [ ] Rename QA milestone to '$version' and close it

**Comment by pmaier1** [comment]
Closing in favor of https://github.com/owncloud/impersonate/issues/67
