### ISSUE TITLE
0.1.1 release plan

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/impersonate#67]
Open
- https://github.com/owncloud/impersonate/issues/38
- https://github.com/owncloud/impersonate/issues/64
- https://github.com/owncloud/impersonate/issues/66

QA 
- [x]  [Upgrade release branch or create it again](http://endoflineblog.com/oneflow-a-git-branching-model-and-workflow#starting-a-release-branch)
- [x] create testplan and test cases Link: https://github.com/owncloud/impersonate/issues/56
- [x] test and document in testplan, including know issues. Final release "Go"

Build

- [x] Bump version in info.xml #77
- [x] Adapt CHANGELOG.md https://github.com/owncloud/impersonate/issues/71
- [x] Change CHANGELOG.md 'Unreleased' to '$version' and add a new 'Unreleased' section
- [x] create release tag on github (by @patrickjahns )
- [x] Sign and build tarball (by @patrickjahns )
- [x] Upload to marketplace (by @patrickjahns )
- [x] Rename QA milestone to '$version' (by @patrickjahns )

@DeepDiver1975 there are open bugs, but I think it is better to release this now and when @sharidas is available again to fix them, make another release.

**Comment by SergioBertolinSG** [comment]
@pmaier1 be aware that there are open bugs but we want to release this app as soon as possible.

**Comment by pmaier1** [comment]
> @pmaier1 be aware that there are open bugs but we want to release this app as soon as possible.

Yes, I know. We should nevertheless get a release out now for the security fix and tackle the other issues afterwards.

**Comment by patrickjahns** [comment]
@pmaier1 
app has been released, please close accordingly if there are no more tasks to be done

**Comment by Emil-G** [comment]
@patrickjahns @pmaier1 , don't close. The released app is missing a change-log.

**Comment by pmaier1** [comment]
> @patrickjahns @pmaier1 , don't close. The released app is missing a change-log.

Yes, we know. This was done unintentionally and the next release will contain a changelog again.

Once https://github.com/owncloud/impersonate/pull/78 is merged you will find the changelog (https://github.com/owncloud/impersonate/blob/release/CHANGELOG.md) here https://github.com/owncloud/impersonate/blob/master/CHANGELOG.md. Closing.
